---
- name: Update package cache
  ansible.builtin.apt:
    update_cache: true

- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Configure nginx.conf
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: '0644'
  notify: Restart Nginx

- name: Copy index.html
  ansible.builtin.copy:
    src: index.html
    dest: /var/www/html/index.html
    mode: '0644'
    
- name: Run Nginx in foreground
  ansible.builtin.shell:
    cmd: nginx -g "daemon off;"
  async: 60
  poll: 0
  environment:
    MY_VAR: "test"
  register: nginx_result
  failed_when:
    - nginx_result is failed
    - "'Address already in use' not in nginx_result.msg"
