all:
  hosts:
    server1:
      ansible_host: localhost
      ansible_port: 221
    server2:
      ansible_host: localhost
      ansible_port: 222
    server3:
      ansible_host: localhost
      ansible_port: 223
    server4:
      ansible_host: localhost
      ansible_port: 224
    server5:
      ansible_host: localhost
      ansible_port: 225
    server6:
      ansible_host: localhost
      ansible_port: 226
    server7:
      ansible_host: localhost
      ansible_port: 227
    server8:
      ansible_host: localhost
      ansible_port: 228
    server9:
      ansible_host: localhost
      ansible_port: 229
  vars:
    ansible_user: root
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
