name: Ansible CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ansible-checks:
    name: Проверка и тестирование Ansible
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Получение кода
        uses: actions/checkout@v4

      - name: 🔧 Установка Ansible
        run: |
          sudo apt update
          sudo apt install -y software-properties-common
          sudo add-apt-repository --yes --update ppa:ansible/ansible
          sudo apt install -y ansible

      - name: 🔍 Проверка синтаксиса плейбуков
        run: |
          ansible-playbook --syntax-check playbooks/*.yml

      - name: 🧹 Проверка с помощью ansible-lint
        run: |
          sudo apt install -y ansible-lint
          ansible-lint playbooks/*.yml

      - name: 🐳 Установка Docker
        run: |
          # Удаление старых версий (если были)
          sudo apt remove -y docker docker-engine docker.io containerd runc || true
      
          # Очистка пакетов
          sudo apt autoremove -y
      
          # Установка зависимостей
          sudo apt update
          sudo apt install -y ca-certificates curl gnupg
      
          # Добавление GPG-ключа Docker
          sudo install -m 0755 -d /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg  | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      
          # Добавление репозитория Docker
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu  \
            $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      
          # Обновление списка пакетов
          sudo apt update
      
          # Установка Docker
          sudo apt install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
      
          # Проверка установки
          docker --version
          sudo docker run hello-world

      - name: 🧱 Сборка Docker-образа
        run: |
          docker build -t ubuntu-sshd ./files/

      - name: 🚀 Запуск тестового контейнера
        run: |
          docker run -d --name server1 -p 2201:22 -p 8001:80 ubuntu-sshd

      - name: 🔐 Настройка SSH-ключа
        run: |
          ssh-keygen -t rsa -b 4096 -N "" -f ~/.ssh/id_rsa
          cat ~/.ssh/id_rsa.pub | ssh root@localhost -p 2201 "mkdir -p /root/.ssh && cat >> /root/.ssh/authorized_keys"
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock

      - name: 🧪 Тестирование плейбука
        run: |
          ansible-playbook -i hosts.yml playbooks/deploy-nginx.yml --check

      - name: 🧾 Отправка отчета (опционально)
        if: ${{ failure() }}
        run: |
          echo "❌ Тестирование завершено с ошибками!"
